version: '3'
services:
  nginx:
    build: ./backend/nginx
    links:
      - node:node
    ports:
      - "3000:8081"
  node:
    build: ./backend/node
    ports:
      - 8082
    volumes:
      - ./backend/node/:/app/
      - /app/node_modules/
    links:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: