version: '3'
services:
  nginx:
    build: ./nginx
    links:
      - node:node
    ports:
      - "3000:8081"
  node:
    build: ./node
    ports:
      - 8082
    volumes:
      - ./node/:/app/
      - /app/node_modules/
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: