# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Anand Mani Sankar

# Copy custom configuration file from the current directory
COPY config.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 8081
